# Generated by Django 3.2.16 on 2022-12-23 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecobot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='mdt',
            new_name='dateTime',
        ),
        migrations.RenameField(
            model_name='user_info',
            old_name='mtext',
            new_name='text',
        ),
    ]
