# Generated by Django 3.0.3 on 2022-06-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20220606_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='http://127.0.0.1:8000/shop/static/img/'),
        ),
    ]
